---
- name: configuration play 
  hosts: web
  user: ubuntu
  become: true
  gather_facts: false
  tasks:
  
  - name: install dependencies
    become: yes
    apt:
      update_cache: yes
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      state: latest
  - name: Installing docker - GPG key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: adding repository docker
    become: yes
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present
  - name: install docker
    become: yes
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest
  - name: Install docker-compose
    become: yes
    get_url:
      url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: '755'
  - name: Get/Update Code
    become: yes
    git:
      repo: https://github.com/Fouty7/Github-Action-Docker-Deployment.git
      dest: /home/ubuntu/github-action
      clone: yes
      update: yes

  - name: start docker compose
    become: yes
    shell: |
      cd github-action
      docker image ls
      docker compose up -d --build

  - name: cleanup old images
    become: yes
    ignore_errors: true
    shell: |
      docker rmi $(docker images --filter "dangling=true" -q --no-trunc)