---
- hosts: all
  become: true
  tasks: 
    - name: Update all servers
      tags: always
      package:
        update_cache: yes
    
- hosts: terraform_server
  become: true
  roles:
    - terraform_server
  

- hosts: web_servers
  become: true
  gather_facts: false
  roles:
    - web_servers


- hosts: db_server
  tags: db, mysql
  become: true
  gather_facts: false
  roles:
    - db_server
