---

- hosts: all
  become: true
  tasks:

  - name: Install apache2 and php packages using apt
    apt:
      update_cache: yes
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in  ["Ubuntu", "Debian"]

  - name: Install httpd and php using dnf
    ansible.builtin.dnf:
      update_cache: yes
      name: 
        - httpd
        - php
      state: latest
      use_backend: dnf4
    when: ansible_distribution in  ["Amazon", "CentOS"]